config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    collection do
      post :confirm
    end
  end
  root 'sessions#new'
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
   validates :title, presence: true, uniqueness: true, length:{ maximum:100}
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :content, presence: true

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord

  validates :first_name, presence: true, length: {maximum: 30}

  validates :last_name, presence: true, length: {maximum: 30}

  validates :email, presence: true, length: {maximum: 255}, uniqueness: true,
  format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  before_validation {email.downcase!}

  has_secure_password

  validates :password, :password_confirmation, presence: true, length: {minimum: 6}

  validates :gender, presence: true

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :login_required

  skip_before_action :login_required, only: [:new, :create]

  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  def confirm
    @post = Post.new(post_params)
    @post = current_user.posts.build(post_params)
    render :new if @post.invalid?
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def confirm
    @post =Post.new(post_params)
    @post.user_id = current_user.id
    render :new if @post.invalid?
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:content, :image, :user_id, :image_cache)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)

    if user && user.authenticate(params[:session][:password])
        session[:user_id] = user.id
        redirect_to posts_path
    else
      flash[:danger] = 'Failed to login'
      redirect_to new_session_path
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'You logged out'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to new_session_path, notice: "You have signed up successfully! Log in now."
    else
      render :new, notice: "Failed to sign up"
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :gender)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def choose_new_or_edit
        if action_name == 'new' || action_name == 'create'
            confirm_posts_path
        elsif action_name == 'edit'
            post_path
        end
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end

    def logged_in?
        current_user.present?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fbclone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->

    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
            crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>

  </head>

  <body>
    <% if flash[:notice] %>
      <div class="bg-success card col-8 mt-2 ml-5">
        <p class="notice text-white"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="bg-danger card col-8 mt-2 ml-5">
        <p class="alert text-white"><%= alert %></p>
      </div>
    <% end %>


    <div class="d-flex flex-column flex-md-row align-items-center fixed-top p-2 px-md-4 mb-2 bg-white border-bottom shadow-sm">
        <h3 class="my-0 mr-md-auto font-weight-bold text-primary">facebook</h3>
        <nav class="my-2 my-md-0 mr-md-3">
          <% if logged_in? %>
          <div class="mt-2 float-right">
            <%= link_to "Profile", user_path(current_user.id), class: "p-2 text-primary"%>
            <%= link_to "Logout", session_path(current_user.id), method: :delete, class: "p-2 text-primary"%>
          </div>

          <% else %>
          <div class="mt-2 float-right">
            <%= link_to "Sign up", new_user_path, class: "p-2 text-primary" %>
            <%= link_to "Login", new_session_path, class: "p-2 text-primary" %>
          </div>
          <% end %>
        </nav>
    </div>

    <%= yield %>
    <!-- Footer -->
    <footer class="pt-4 mt-5 bg-white">
      <div class="container-fluid text-center text-md-left">
        <div class="footer-copyright text-center py-3">© 2020 Copyright
          <a href="#"> Nos conditions & politique de confidentialité</a>
        </div>
      </div>
    </footer>

  </body>
</html>

app/views/posts/_form.html.erb
<div class="container" style="margin-top:120px;">
  <%= form_with(model: post, local:true, url: choose_new_or_edit) do |form| %>
    <% if post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
          <% post.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="card gedf-card">
        <div class="card-header">
            <ul class="nav nav-tabs card-header-tabs" id="myTab" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" id="posts-tab" data-toggle="tab" href="#posts" role="tab" aria-controls="posts" aria-selected="true">Make
                        a publication</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="images-tab" data-toggle="tab" role="tab" aria-controls="images" aria-selected="false" href="#images">Images</a>
                </li>
            </ul>
        </div>
        <div class="card-body">
            <div class="tab-content" id="myTabContent">
                <div class="tab-pane fade show active" id="posts" role="tabpanel" aria-labelledby="posts-tab">
                    <div class="form-group">
                        <%= form.label :content, class: "sr-only", for: "message" %>
                        <%= form.text_area :content, class: "form-control", id:"message", rows: "3", placeholder: "Write..." %>
                    </div>
                </div>
                <div class="tab-pane fade" id="images" role="tabpanel" aria-labelledby="images-tab">
                    <div class="form-group">
                        <div class="custom-file">
                            <%= form.file_field :image, class: "custom-file-input", id: "customeFile" %>
                            <%= image_tag(post.image.url) if post.image && post.image.url %>
                            <%= form.label :image, class: "custom-file-label", for: "customFile" %>
                            <%= form.hidden_field :image_cache %>
                        </div>
                    </div>
                    <div class="py-4"></div>
                </div>
            </div>
            <div class="btn-toolbar justify-content-between">
                <div class="btn-group">
                    <%= form.submit "Publish", class:"btn btn-primary"%>
                </div>
                <div class="btn-group">
                    <%= link_to 'Back', posts_path, class:"btn btn-danger" %>
                </div>
            </div>
        </div>
    </div>
  <% end %>
</div>

app/views/posts/confirm.html.erb
<div class="container" style="margin-top:120px;">
    <h3 class="mt-5 mb-5">Confirm this post</h3>

    <%= form_with(model: @post, url: posts_path, local: true, method:'post') do |form| %>
      <div class="card gedf-card">
          <div class="card-header">
              <ul class="nav nav-tabs card-header-tabs" id="myTab" role="tablist">
                  <li class="nav-item">
                      <a class="nav-link active" id="posts-tab" data-toggle="tab" href="#posts" role="tab" aria-controls="posts" aria-selected="true">Make
                          a publication</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" id="images-tab" data-toggle="tab" role="tab" aria-controls="images" aria-selected="false" href="#images">Images</a>
                  </li>
              </ul>
          </div>
          <div class="card-body">
              <div class="tab-content" id="myTabContent">
                  <div class="tab-pane fade show active" id="posts" role="tabpanel" aria-labelledby="posts-tab">
                      <div class="form-group">
                          <p>Content: <%= @post.content %></p>
                          <%= form.hidden_field :content, class: "form-control"%>
                      </div>
                  </div>
                  <div class="tab-pane fade" id="images" role="tabpanel" aria-labelledby="images-tab">
                      <div class="form-group">
                          <div class="custom-file">
                              <% if @post.image && @post.image.url %>
                                <%= image_tag @post.image.url, class: 'img-fluid mb-5', style:"width:400px;" %>
                              <% end %>
                              <%= form.hidden_field :image_cache %>
                          </div>
                      </div>
                      <div class="py-4"></div>
                  </div>
              </div>
              <div class="btn-toolbar justify-content-between mt-5">
                  <div class="btn-group">
                      <%= form.submit "Confirm", class:"btn btn-primary"%>
                  </div>
                  <% end %>
                  <div class="btn-group">
                    <%= form_with(model:@post, url:new_post_path, local:true, method:"get") do |form| %>
                      <%= form.hidden_field :image_cache %>
                      <%= form.submit "Return", name: "back", class: "btn btn-danger" %>
                    <% end %>
                  </div>
              </div>
          </div>
      </div>
</div>

app/views/posts/edit.html.erb
<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid" style="margin-top:100px;">
    <div class="row">
        <div class="col-md-3 mb-5 mt-4">
            <div class="card mb-5">
                <div class="card-body">
                    <div class="h5"><%= current_user.first_name %></div>
                    <div class="h7 text-muted">Fullname : <%= current_user.last_name %></div>
                    <div class="h7">Developer of web applications, JavaScript, PHP, Java, Python, Ruby, Java, Node.js,
                        etc.
                    </div>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <div class="h6 text-muted">Followers</div>
                        <div class="h5">5.2342</div>
                    </li>
                    <li class="list-group-item">
                        <div class="h6 text-muted">Following</div>
                        <div class="h5">6758</div>
                    </li>
                    <li class="list-group-item">En ligne il y 2h</li>
                </ul>
            </div>
            <div class="card">
                <div class="card-body">
                    <div class="h5"><%= current_user.first_name %></div>
                    <div class="h7 text-muted">Fullname : <%= current_user.last_name %></div>
                    <div class="h7">Developer of web applications, JavaScript, PHP, Java, Python, Ruby, Java, Node.js,
                        etc.
                    </div>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <div class="h6 text-muted">Followers</div>
                        <div class="h5">5.2342</div>
                    </li>
                    <li class="list-group-item">
                        <div class="h6 text-muted">Following</div>
                        <div class="h5">6758</div>
                    </li>
                    <li class="list-group-item">En ligne il y 2h</li>
                </ul>
            </div>
        </div>
        <div class="col-md-6 gedf-main mb-5 mt-4">
            <%= link_to 'New Post', new_post_path, class:"btn btn-block btn-primary text-center mb-4" %>

            <% @posts.each do |post| %>
              <div class="card gedf-card mb-5 mt-5">
                  <div class="card-header">
                      <div class="d-flex justify-content-between align-items-center">
                          <div class="d-flex justify-content-between align-items-center">
                              <div class="mr-2">
                                  <img class="rounded-circle" width="45" src="https://picsum.photos/50/50" alt="">
                              </div>
                              <div class="ml-2">
                                  <div class="h5 m-0">
                                    <%= current_user.first_name %>
                                  </div>
                                  <div class="h7 text-muted">
                                    <%= current_user.first_name + " a publié" %>
                                  </div>
                              </div>
                          </div>
                          <div>
                              <div class="dropdown">
                                  <button class="btn btn-link dropdown-toggle" type="button" id="gedf-drop1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                      <i class="fa fa-ellipsis-h"></i>
                                  </button>
                                  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="gedf-drop1">
                                      <div class="h6 dropdown-header">Configuration</div>
                                      <%= link_to 'Show', post, class:"dropdown-item" %>
                                      <%= link_to 'Edit', edit_post_path(post), class:"dropdown-item" %>
                                      <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class:"dropdown-item" %>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
                  <div class="card-body">
                      <div class="text-muted h7 mb-2"> <i class="fa fa-clock-o"></i>10 min ago</div>

                      <div class="mb-3">
                        <img src="<%= post.image %>" class="img-fluid" alt="">
                      </div>
                      <p class="card-text">
                        <%= post.content %>
                      </p>
                  </div>
                  <div class="card-footer">
                      <a href="#" class="card-link"><i class="fa fa-gittip"></i> Like</a>
                      <a href="#" class="card-link"><i class="fa fa-comment"></i> Comment</a>
                      <a href="#" class="card-link"><i class="fa fa-mail-forward"></i> Share</a>
                  </div>
              </div>
            <% end %>

            <iframe src="https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fweb.facebook.com%2FFlo2Fla%2Fposts%2F386045719546148&show_text=true&width=500" width="500" height="666" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowfullscreen="true" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share" class="mb-5 mt-3">
            </iframe>

            <iframe src="https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fweb.facebook.com%2Fsamuel.mevognon.5%2Fposts%2F883175722618878&show_text=true&width=500" width="500" height="471" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowfullscreen="true" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share"></iframe>
        </div>
        <div class="col-md-3 mb-5 mt-4">
            <div class="card gedf-card">
                <div class="card-body">
                    <h5 class="card-title">Sugestions de groupes</h5>
                    <h6 class="card-subtitle mb-2 text-muted">Les hackers</h6>
                    <p class="card-text">Page exclusivement dediée au partage de connaissances en piratage informatique</p>
                    <a href="#" class="card-link btn btn-primary">Rejoindre</a>
                    <a href="#" class="card-link">Ne plus voir</a>
                </div>
            </div>
            <div class="card gedf-card mb-5 mt-4">
                <div class="card-body">
                    <h5 class="card-title">Evenements</h5>
                    <h6 class="card-subtitle mb-2 text-muted">Ino's </h6>
                    <p class="card-text">Aujourd'hui c'est l'anniversaire de Inos'B</p>
                </div>
            </div>
            <div class="card gedf-card">
                <div class="card-body">
                    <h5 class="card-title">Sugestions de groupes</h5>
                    <h6 class="card-subtitle mb-2 text-muted">Les prof d web</h6>
                    <p class="card-text">Page exclusivement dediée au partage de connaissances en piratage informatique</p>
                    <a href="#" class="card-link btn btn-primary">Rejoindre</a>
                    <a href="#" class="card-link">Ne plus voir</a>
                </div>
            </div>
            <div class="card gedf-card">
                <div class="card-body">
                    <h5 class="card-title">Sugestions de groupes</h5>
                    <h6 class="card-subtitle mb-2 text-muted">Les PROGRAMMEURS</h6>
                    <p class="card-text">Page exclusivement dediée au partage de connaissances en programmation informatique</p>
                    <a href="#" class="card-link btn btn-primary">Rejoindre</a>
                    <a href="#" class="card-link">Ne plus voir</a>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/posts/new.html.erb
<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid" style="margin-top:100px;">
  <div class="row">
    <div class="col-3">
    </div>
    <div class="col-md-6 gedf-main mb-5 mt-4">
        <div class="card gedf-card">
            <div class="card-header">
                <div class="d-flex justify-content-between align-items-center">
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="mr-2">
                            <img class="rounded-circle" width="45" src="https://picsum.photos/50/50" alt="">
                        </div>
                        <div class="ml-2">
                            <div class="h5 m-0">
                              <%= current_user.first_name %>
                            </div>
                            <div class="h7 text-muted">
                              <%= current_user.first_name + " a publié" %>
                            </div>
                        </div>
                    </div>
                    <div>
                        <div class="dropdown">
                            <button class="btn btn-link dropdown-toggle" type="button" id="gedf-drop1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fa fa-ellipsis-h"></i>
                            </button>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="gedf-drop1">
                                <div class="h6 dropdown-header">Configuration</div>
                                <%= link_to 'Edit', edit_post_path(@post), class: "dropdown-item" %>
                                <%= link_to 'Back', posts_path, class: "dropdown-item" %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <div class="text-muted h7 mb-2"> <i class="fa fa-clock-o"></i>10 min ago</div>

                <div class="mb-3">
                  <%= image_tag @post.image.url, class:"img-fluid" %>
                </div>
                <p class="card-text">
                  <%= @post.content %>
                </p>
            </div>
            <div class="card-footer">
                <a href="#" class="card-link"><i class="fa fa-gittip"></i> Like</a>
                <a href="#" class="card-link"><i class="fa fa-comment"></i> Comment</a>
                <a href="#" class="card-link"><i class="fa fa-mail-forward"></i> Share</a>
                <%= link_to 'Back', posts_path, class:"card_link" %>
            </div>
        </div>
    </div>
    <div class="col-3">
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="container" style="margin-top:10%;">
  <div class="row" style="margin-top:3%;">
    <div class="col-sm-6" style="margin-top:50px;">
      <h1 class="text-primary">facebook</h1>
      <p>Avec facebook partagez et restez en contact avec votre entourage, <br>Inscrivez vous gratuitement</p>
    </div>
    <div class="col-sm-6">
      <div class="card">
        <h2 class="text-center text-primary mt-3">Create account</h2>
        <div class="card-body">
          <%= form_with(model: @user, local: true) do |f| %>
            <div class="field form-group">
              <%= f.text_field :first_name, placeholder: "first name" ,class: "form-control" %>
            </div>
            <div class="field form-group">
              <%= f.text_field :last_name, placeholder: "last name" ,class: "form-control" %>
            </div>
            <div class="field form-group">
              <%= f.email_field :email, placeholder: "email" ,class: "form-control" %>
            </div>
            <div class="field form-group">
              <%= f.password_field :password, placeholder: "password" ,class: "form-control" %>
            </div>
            <div class="field form-group ">
                <%= f.password_field :password_confirmation ,placeholder: "Confirm Password", class: "form-control f3" %>
            </div>
            <hr>
            <div class="field">
                <%= f.label :gender, "Female", :value => "female"%>
                <%= f.radio_button :gender, "female" %>
                <%= f.label :gender, "Male", :value => "male" %>
                <%= f.radio_button :gender, "male" %>
            </div>

            <%= f.submit "Sign Up" ,class:"btn btn-success btn-block text-white text-center"%>
          <% end %>
          <hr>
          <p>If you have account</p>
          <a href="<%= new_session_path %>" class="btn btn-primary btn-lg btn-block text-white">Login</a>
       </div>
     </div>
    </div>
  </div>
<div>

app/views/users/new.html.erb
<%= render 'form', user: @user %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row" style="margin-top:100px;">
  <div class="col-3">

  </div>
  <div class="col-6 mt-5">
    <div class="card">
      <h2 class="card-title text-info mt-2 text-center">Your Informations</h2>
      <div class="card-body">
        <p><span class="text-primary">First Name:</span> <%= @user.first_name %></p>
        <p><span class="text-primary">Last Name:</span> <%= @user.last_name %></p>
        <p><span class="text-primary">Email Adress:</span> <%= @user.email%></p>
        <p><span class="text-primary">Gender:</span> <%= @user.gender %></p>
      </div>
    </div>
    <%= link_to 'Back', posts_path, class:"btn btn-danger btn-block mt-3" %>
  </div>

  <div class="col-3">

  </div>
</div>